version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    ports:
      - "80:80"

  app:
    build: .
    container_name: app
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    stdin_open: true
    tty: true
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
