version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    ports:
      - "80:80"

  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./:/var/www

  octane:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: octane
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./:/var/www
    command: ["/usr/local/bin/php", "/var/www/laravel/artisan", "octane:start", "--server=roadrunner", "--workers=48", "--host=0.0.0.0", "--port=8000"]

  webman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webman
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    ports:
      - "8001:8001"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./:/var/www
    command: ["/usr/local/bin/php", "/var/www/webman/start.php", "start"]

  adapterman:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adapterman
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
    ports:
      - "8002:8002"
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./:/var/www
    command: [ "/usr/local/bin/php", "/var/www/laravel/server.php", "start" ]
